-- Chamados (suporte) — melhorias:
--   • ticket_number: código sequencial legível (#1, #2, …). Identity preenche os
--     chamados já existentes na criação da coluna (rewrite da tabela pequena).
--   • assignee_id: responsável pelo chamado (um admin). Quando definido, passa a
--     ser o único destinatário dos e-mails daquele chamado (regra na aplicação).

alter table public.support_tickets
  add column if not exists ticket_number bigint generated by default as identity;
create unique index if not exists support_tickets_number_uidx
  on public.support_tickets (ticket_number);

alter table public.support_tickets
  add column if not exists assignee_id uuid references public.users(id);
create index if not exists support_tickets_assignee_idx
  on public.support_tickets (assignee_id);

-- A atualização de assignee_id (como status/prioridade) já é coberta pela policy
-- support_tickets_update (is_admin()); nada novo de RLS é necessário.
